name: input examples

on:
  workflow_dispatch:
    inputs:
      app_name: 
        description: "Application Name"
        required: true
        type: string
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: example
        run: echo ${{ inputs.app_name }}
