name: Build Application with parameters

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
      - uses: actions/checkout@v4
      - name: build-application
      - run: echo "Building project..."
      