name: Testing-triggers

# on:
#   pull_request:

on: 
  pull_request:
    branches:
      - develop


jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: anc testing
        run: ls